on:
  push:
    branches:
      - deploy
name: 🚀 Deploy website on push
jobs:
  build:
    name: 🔨 Build
    runs-on: ubuntu-latest
    steps:

    - name: 🔨 Install Packages
      run: npm ci

    - name: 🔨 Build App
      run: npm run build

    - name: 🧨 Archive production artifact
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build

  deploy:
    name: 🏬 Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 🧨 Download artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ftp.laboratorberceanu.ro
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}